# Generated by Django 2.0.1 on 2018-04-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorInfo',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('ad_username', models.CharField(max_length=32)),
                ('ad_password', models.CharField(max_length=64)),
            ],
        ),
    ]
