# Generated by Django 2.0.1 on 2018-04-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administratorinfo',
            old_name='ad_username',
            new_name='ad_phone',
        ),
    ]
