# Generated by Django 2.0.1 on 2018-04-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180415_0104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdministratorInfo',
        ),
    ]
