# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-23 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20180423_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
