# Generated by Django 2.0.1 on 2018-04-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20180423_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorInfo',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('ad_phone', models.CharField(max_length=32)),
                ('ad_password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='NewsInfo',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('news_title', models.CharField(max_length=120)),
                ('news_details', models.CharField(max_length=600)),
                ('news_time', models.DateField(max_length=20)),
            ],
        ),
    ]
