# Generated by Django 2.0.1 on 2018-04-27 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_npticeinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NpticeInfo',
            new_name='NoticeInfo',
        ),
    ]
