# Generated by Django 2.0.1 on 2018-04-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20180428_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_name', models.CharField(max_length=32)),
                ('user_phone', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('user_sex', models.CharField(max_length=4)),
                ('user_type', models.CharField(max_length=10)),
                ('user_number', models.CharField(max_length=32)),
                ('user_birth', models.DateField(max_length=16)),
            ],
        ),
    ]
