# Generated by Django 2.0.1 on 2018-05-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionInfo',
            fields=[
                ('competition_username', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('competition_userphone', models.CharField(max_length=32)),
                ('competition_type', models.CharField(max_length=32)),
                ('competition_details', models.CharField(max_length=32)),
                ('competition_time', models.DateField(max_length=20)),
            ],
        ),
    ]
